export enum PluginEvent {
  BotStartup,
  ChatInitialisation,
  ChatMessage,
  PreDankTime,
  PostDankTime,
  PreUserScoreChange,
  PostUserScoreChange,
  LeaderboardPost,
  ChatReset,
  HourlyTick,
  NightlyUpdate,
  BotShutdown,
  Custom,
}
